### ISSUE TITLE
missing file in Google Drive

### ISSUE THREAD

**Issue by zuozhen** [tg-bomze/BabyGAN#10]
There's no "finetuned_resnet.h5" and "karras2019stylegan-ffhq-1024x1024.pkl" in Google Drive, please help check. 
Thanks.

**Comment by zuozhen** [comment]
I found these two file from another repo: https://github.com/pbaylies/stylegan-encoder/blob/master/README.md
So, close this issue.

**Comment by zahrasadat9** [comment]
@zuozhen  I cant find the 'finetuned_resnet.h5' in the link you provided :(

**Comment by MustafaCQN** [comment]
@zuozhen Can you specify the path of the file with link?

**Comment by zuozhen** [comment]
@zahrasadat9 @MustafaCQN 
Well, that was a long time ago, I don't do deep-learning-work now.
And I found that I could not find 'finetuned_resnet.h5' in this repo 'https://github.com/pbaylies/stylegan-encoder/tree/master' either. 
But from this line "The ResNet encoder - train your own with train_resnet.py and put the model in data/finetuned_resnet.h5" mentioned in the readme of that repo, it seems that you can generate your own 'finetuned_resnet.h5'.
Hope this helps, good luck.
